import Head from 'next/head'
import { signOut, useSession } from "next-auth/react";

import axios from 'axios';
import Link from 'next/link'
import { useEffect, useState } from 'react';
import io from 'socket.io-client'
import Chat from '@/components/chat';

const socket = io()
export default function Home() {
  
  const { data: session } = useSession();
  const [in_room, setInRoom] = useState(false);
  const [username, setUsername] = useState("");
  // const [allMessages,setAllMessages]=useState([])
  useEffect(() => {
    fetch('/api/socket').finally(() => {
 

      socket.on('connect', () => {
        alert("hi")
      })

      socket.on('disconnect', () => {
        console.log('disconnect')
      })
    })
  }, [])

  async function  handleSubmit (e) {
    e.preventDefault()
    socket.emit("join_room",'room1')
    setInRoom(true)
  
  }

  // const createRoom=async ()=>{
  //   socket.emit("join_room",{id:"test",namer:"bag"})
  // }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="" >

        {session?.user ? (
          <>
               {!in_room && <button onClick={handleSubmit} className='bg-amber-600 py-4 px-7 rounded-xl'>Open chat</button>}
               { in_room &&
                <Chat socket={socket} username={session?.user.name} room={"room1"}/>
               }
      

          <div className="flex mx-auto gap-2 w-fit">

       
      
            <button
              onClick={() => signOut()}
              className=" rounded-3xl mt-4 text-center p-2 bg-orange-900 text-white block mx-auto w-fit px-4"
            >
              Logout
            </button>
          </div>
          </>
        ) : (
          <Link
            href="/auth/login"
            className="rounded-3xl mt-4 text-center p-2 bg-green-600  text-white block mx-auto w-fit px-4"
          >
            Signin to join the conference
          </Link>
        )}
      </main>
    </>
  )
}
